# included:
#   - Source
#   - Tests
variable_name:
  min_length:
    warning: 2
opt_in_rules: # some rules are only opt-in
  - empty_count
  - file_header
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - prohibited_super_call
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Vendors
  - Carthage
  - Pods
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Tomo
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} e-business\. All rights reserved\.
                    \/\/
